permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 8
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "Euraxluo"  #blog name
email: "1793939176@qq.com" #email
description: "NLPer 泛语言编程者" #简介
github_username:  "saucu-li" #github
sidebar-avatar: "wxtouxiang.png" #头像
staticimg: "https://saucu-li.github.io/static/img" #网站静态资源

swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm" #搜索库
disqus_shortname: "rainyalley" #评论




url: "https://saucu-li.github.io" #博客地址
imgrepo: "https://saucu-li.github.io/img" #博客图床


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

