permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 8
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "博客名"  #blog name
email: "email@qq.com" #email
description: "工程师" #简介
github_username:  "saucu-li" #github
sidebar-avatar: "static/img/wxtouxiang.png" #头像
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm" #搜索库
disqus_shortname: "rainyalley" #评论
staticimg: "https://saucu-li.github.io/static/img" #图床



url: "https://saucu-li.github.io" #博客地址
imgrepo: "https://saucu-li.github.io/img" #图床


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

